#!/bin/python3

import random
import argparse

parser = argparse.ArgumentParser("Prints a random number between the given lower and upper bounds to stdout")
parser.add_argument("minimum", type=int, default=0, help="The inclusive lower bound of numbers to generate.")
parser.add_argument("maximum", type=int, default=65536, help="The exlusive upper bound of numbers to generate.")
args=parser.parse_args()

print(random.randint(args.minimum,args.maximum))

